apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-addition-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-addition
  template:
    metadata:
      labels:
        app: flask-addition
    spec:
      containers:
      - name: flask-addition
        image: your-dockerhub-username/flask-addition:latest
        ports:
        - containerPort: 5000
